name: maquinaJava

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Revisar repositorio
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Ejecutar pruebas unitarias
        working-directory: UsuarioAPI
        run: mvn test

      - name: Subir reporte de pruebas (Surefire)
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: UsuarioAPI/target/surefire-reports/


      - name: Crear carpeta en el server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /home/ubuntu/UsuarioAPI
            chmod 755 /home/ubuntu/UsuarioAPI

      - name: Sincronizar archivos con el servidor EC2
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: "-avzh --delete --exclude=.git/"
          path: "./"
          remote_host: ${{ secrets.IP_SERVER }}
          remote_user: ${{ secrets.USERNAME }}
          remote_path: "/home/ubuntu/UsuarioAPI/"
          remote_key: ${{ secrets.PRIVATE_KEY }}
          remote_port: ${{ secrets.PORT }}

      - name: Lanzamiento de contenedores en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/UsuarioAPI
            sudo docker compose down --remove-orphans --timeout 120
            sudo docker compose up -d --build --force-recreate
            sudo docker system prune -f
